name: CI Build LedFx Frontend v2

on:
  push:
    branches:
      - frontend_beta
  pull_request:
    branches:
      - frontend_beta

jobs:
  build-ledfx-frontend-v2:
    name: Build LedFx Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3
        with:
          repository: YeonV/LedFx-Frontend-v2
          ref: main
          # path: ledfx-frontend-v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Run yarn install and build
        run: |
          yarn
          yarn buildgh
        env:
          CI: true


