name: Create Sentry Dev Release

on:
  push:
    branches:
      - frontend_beta

jobs:
  sentry-release:
    name: Create sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3
      - name: Create sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ledfx-org
          SENTRY_PROJECT: ledfx-betas-v2
        with:
          environment: development
          finalize: false